-- MySQL Script generated by MySQL Workbench
-- Sat Mar 19 20:29:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema testsire
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testsire
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testsire` DEFAULT CHARACTER SET utf8 ;
USE `testsire` ;

-- -----------------------------------------------------
-- Table `testsire`.`template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testsire`.`template` (
  `idTemplate` INT NOT NULL,
  `NombreTemplate` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`idTemplate`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `testsire`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testsire`.`pregunta` (
  `idPregunta` INT NOT NULL,
  `descPregunta` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`idPregunta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `testsire`.`bancopreguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testsire`.`bancopreguntas` (
  `fk_idPregunta` INT NOT NULL,
  `fk_idTemplate` INT NOT NULL,
  `tipoPregunta` TINYINT NOT NULL,
  PRIMARY KEY (`fk_idPregunta`, `fk_idTemplate`),
  INDEX `fk_Cuestionario_has_Pregunta_Pregunta1_idx` (`fk_idPregunta` ASC) VISIBLE,
  INDEX `fk_BancoPreguntas_Template1_idx` (`fk_idTemplate` ASC) VISIBLE,
  CONSTRAINT `fk_BancoPreguntas_Template1`
    FOREIGN KEY (`fk_idTemplate`)
    REFERENCES `testsire`.`template` (`idTemplate`),
  CONSTRAINT `fk_Cuestionario_has_Pregunta_Pregunta1`
    FOREIGN KEY (`fk_idPregunta`)
    REFERENCES `testsire`.`pregunta` (`idPregunta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `testsire`.`chapter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testsire`.`chapter` (
  `idChapter` INT NOT NULL,
  `nombreCh` VARCHAR(128) NOT NULL,
  `nEmpleados` INT NOT NULL,
  PRIMARY KEY (`idChapter`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `testsire`.`roljerarquico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testsire`.`roljerarquico` (
  `idRolJer` VARCHAR(15) NOT NULL,
  `descRolJer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRolJer`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `testsire`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testsire`.`empleado` (
  `idEmpleado` INT NOT NULL,
  `fechaIng` DATE NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoP` VARCHAR(45) NOT NULL,
  `apellidoM` VARCHAR(45) NOT NULL,
  `antiguedad` INT NOT NULL,
  `nivPeople` FLOAT NOT NULL,
  `nivCraft` FLOAT NOT NULL,
  `nivBusiness` FLOAT NOT NULL,
  `nivOverall` FLOAT NOT NULL,
  `puesto` VARCHAR(45) NOT NULL,
  `equipo` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fk_idChapter` INT NOT NULL,
  `fk_idRolJer` VARCHAR(15) NOT NULL,
  `isActive` TINYINT NULL DEFAULT '1',
  PRIMARY KEY (`idEmpleado`, `fk_idChapter`, `fk_idRolJer`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `idEmpleado_UNIQUE` (`idEmpleado` ASC) VISIBLE,
  INDEX `fk_Empleado_Chapter1_idx` (`fk_idChapter` ASC) VISIBLE,
  INDEX `fk_Empleado_RolJerarquico1_idx` (`fk_idRolJer` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Chapter1`
    FOREIGN KEY (`fk_idChapter`)
    REFERENCES `testsire`.`chapter` (`idChapter`),
  CONSTRAINT `fk_Empleado_RolJerarquico1`
    FOREIGN KEY (`fk_idRolJer`)
    REFERENCES `testsire`.`roljerarquico` (`idRolJer`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `testsire`.`periodoevaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testsire`.`periodoevaluacion` (
  `idPeriodo` INT NOT NULL,
  `FechaInicio` DATE NOT NULL,
  `FechaFin` DATE NOT NULL,
  PRIMARY KEY (`idPeriodo`),
  UNIQUE INDEX `idPeriodo_UNIQUE` (`idPeriodo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `testsire`.`chaptermood`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testsire`.`chaptermood` (
  `idChapterMood` INT NOT NULL,
  `Mood` INT NULL DEFAULT NULL,
  `Status` TINYINT NOT NULL,
  `fk_idEmpleado` INT NOT NULL,
  `fk_idPeriodo` INT NOT NULL,
  PRIMARY KEY (`idChapterMood`, `fk_idEmpleado`, `fk_idPeriodo`),
  INDEX `fk_ChapterMood_Empleado1_idx` (`fk_idEmpleado` ASC) VISIBLE,
  INDEX `fk_ChapterMood_PeriodoEvaluacion1_idx` (`fk_idPeriodo` ASC) VISIBLE,
  CONSTRAINT `fk_ChapterMood_Empleado1`
    FOREIGN KEY (`fk_idEmpleado`)
    REFERENCES `testsire`.`empleado` (`idEmpleado`),
  CONSTRAINT `fk_ChapterMood_PeriodoEvaluacion1`
    FOREIGN KEY (`fk_idPeriodo`)
    REFERENCES `testsire`.`periodoevaluacion` (`idPeriodo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `testsire`.`cuestionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testsire`.`cuestionario` (
  `idCuestionario` INT NOT NULL,
  `fk_idPeriodo` INT NOT NULL,
  `fk_idEvaluador` INT NOT NULL,
  `fk_idTemplate` INT NOT NULL,
  `idEvaluado` INT NOT NULL,
  `nivelEvaluado` FLOAT NOT NULL,
  `isAnswered` TINYINT NOT NULL,
  PRIMARY KEY (`idCuestionario`, `fk_idPeriodo`, `fk_idEvaluador`, `fk_idTemplate`),
  INDEX `fk_Cuestionario_Empleado1_idx` (`fk_idEvaluador` ASC) VISIBLE,
  INDEX `fk_Cuestionario_Empleado2_idx` (`idEvaluado` ASC) VISIBLE,
  INDEX `fk_Cuestionario_PeriodoEvaluacion1_idx` (`fk_idPeriodo` ASC) VISIBLE,
  INDEX `fk_Cuestionario_Template1_idx` (`fk_idTemplate` ASC) VISIBLE,
  CONSTRAINT `fk_Cuestionario_Empleado1`
    FOREIGN KEY (`fk_idEvaluador`)
    REFERENCES `testsire`.`empleado` (`idEmpleado`),
  CONSTRAINT `fk_Cuestionario_Empleado2`
    FOREIGN KEY (`idEvaluado`)
    REFERENCES `testsire`.`empleado` (`idEmpleado`),
  CONSTRAINT `fk_Cuestionario_PeriodoEvaluacion1`
    FOREIGN KEY (`fk_idPeriodo`)
    REFERENCES `testsire`.`periodoevaluacion` (`idPeriodo`),
  CONSTRAINT `fk_Cuestionario_Template1`
    FOREIGN KEY (`fk_idTemplate`)
    REFERENCES `testsire`.`template` (`idTemplate`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `testsire`.`funcionessistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testsire`.`funcionessistema` (
  `idFuncSis` VARCHAR(15) NOT NULL,
  `Funcion` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`idFuncSis`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `testsire`.`mentees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testsire`.`mentees` (
  `idMentees` INT NOT NULL,
  `fk_idLead` INT NOT NULL,
  `idMentee` INT NULL DEFAULT NULL,
  `descAsignacion` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`idMentees`, `fk_idLead`),
  INDEX `fk_Mentees_Empleado1_idx` (`fk_idLead` ASC) VISIBLE,
  INDEX `fk_Mentees_Empleado2_idx` (`idMentee` ASC) VISIBLE,
  CONSTRAINT `fk_Mentees_Empleado1`
    FOREIGN KEY (`fk_idLead`)
    REFERENCES `testsire`.`empleado` (`idEmpleado`),
  CONSTRAINT `fk_Mentees_Empleado2`
    FOREIGN KEY (`idMentee`)
    REFERENCES `testsire`.`empleado` (`idEmpleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `testsire`.`rolsistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testsire`.`rolsistema` (
  `idRolSis` VARCHAR(15) NOT NULL,
  `RolSis` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRolSis`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `testsire`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testsire`.`permisos` (
  `fk_idRolSis` VARCHAR(15) NOT NULL,
  `fk_idFuncSis` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`fk_idRolSis`, `fk_idFuncSis`),
  INDEX `fk_RolSistema_has_FuncionesSistema_FuncionesSistema1_idx` (`fk_idFuncSis` ASC) VISIBLE,
  INDEX `fk_RolSistema_has_FuncionesSistema_RolSistema1_idx` (`fk_idRolSis` ASC) VISIBLE,
  CONSTRAINT `fk_RolSistema_has_FuncionesSistema_FuncionesSistema1`
    FOREIGN KEY (`fk_idFuncSis`)
    REFERENCES `testsire`.`funcionessistema` (`idFuncSis`),
  CONSTRAINT `fk_RolSistema_has_FuncionesSistema_RolSistema1`
    FOREIGN KEY (`fk_idRolSis`)
    REFERENCES `testsire`.`rolsistema` (`idRolSis`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `testsire`.`preguntarespuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testsire`.`preguntarespuesta` (
  `idRespuesta` INT NOT NULL,
  `idTemplate` INT NULL DEFAULT NULL,
  `idPregunta` INT NULL DEFAULT NULL,
  `fk_idCuestionario` INT NOT NULL,
  `Pregunta` VARCHAR(128) NULL DEFAULT NULL,
  `Respuesta` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`idRespuesta`, `fk_idCuestionario`),
  INDEX `fk_PreguntaRespuesta_Cuestionario_idx` (`fk_idCuestionario` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `testsire`.`registroauth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testsire`.`registroauth` (
  `fk_idEmpleado` INT NOT NULL,
  `fk_idRolSis` VARCHAR(15) NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`fk_idEmpleado`, `fk_idRolSis`),
  INDEX `fk_Empleado_has_RolSistema_RolSistema1_idx` (`fk_idRolSis` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_has_RolSistema_Empleado1`
    FOREIGN KEY (`fk_idEmpleado`)
    REFERENCES `testsire`.`empleado` (`idEmpleado`),
  CONSTRAINT `fk_Empleado_has_RolSistema_RolSistema1`
    FOREIGN KEY (`fk_idRolSis`)
    REFERENCES `testsire`.`rolsistema` (`idRolSis`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `testsire`.`retroalimentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testsire`.`retroalimentacion` (
  `idRetro` INT NOT NULL,
  `Observaciones` VARCHAR(256) NULL DEFAULT NULL,
  `fk_idCuestionario` INT NOT NULL,
  PRIMARY KEY (`idRetro`, `fk_idCuestionario`),
  INDEX `fk_Retroalimentacion_Cuestionario1_idx` (`fk_idCuestionario` ASC) VISIBLE,
  CONSTRAINT `fk_Retroalimentacion_Cuestionario1`
    FOREIGN KEY (`fk_idCuestionario`)
    REFERENCES `testsire`.`cuestionario` (`idCuestionario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
