/*
-- Query: SELECT * FROM testsire.empleado
LIMIT 0, 1000

-- Date: 2022-03-19 20:31
*/
INSERT INTO `` (`idEmpleado`,`fechaIng`,`nombre`,`apellidoP`,`apellidoM`,`antiguedad`,`nivPeople`,`nivCraft`,`nivBusiness`,`nivOverall`,`puesto`,`equipo`,`email`,`password`,`fk_idChapter`,`fk_idRolJer`,`isActive`) VALUES (1,'2021-03-21','Marcos','Polos','Galvez',1,1.3,1.3,1.3,1.3,'Programador','ZeCore Client','marcos.pg@test.com','23456',1,'3',1);
INSERT INTO `` (`idEmpleado`,`fechaIng`,`nombre`,`apellidoP`,`apellidoM`,`antiguedad`,`nivPeople`,`nivCraft`,`nivBusiness`,`nivOverall`,`puesto`,`equipo`,`email`,`password`,`fk_idChapter`,`fk_idRolJer`,`isActive`) VALUES (2,'2021-09-21','Manuel','Medina','Rodriguez',1,2.1,2.1,2.1,2.1,'Programador','ZeCore Client','manolo.mr@test.com','56432',1,'2',1);
INSERT INTO `` (`idEmpleado`,`fechaIng`,`nombre`,`apellidoP`,`apellidoM`,`antiguedad`,`nivPeople`,`nivCraft`,`nivBusiness`,`nivOverall`,`puesto`,`equipo`,`email`,`password`,`fk_idChapter`,`fk_idRolJer`,`isActive`) VALUES (3,'2021-09-21','Felipe','de Borbon','Alvarez',1,2.1,2.2,2.1,2.1,'Supervisor','ZeCore Shipping','felipe.ba@test.com','asdf',1,'2',1);
INSERT INTO `` (`idEmpleado`,`fechaIng`,`nombre`,`apellidoP`,`apellidoM`,`antiguedad`,`nivPeople`,`nivCraft`,`nivBusiness`,`nivOverall`,`puesto`,`equipo`,`email`,`password`,`fk_idChapter`,`fk_idRolJer`,`isActive`) VALUES (4,'2021-09-21','Alvaro','Flores','Alba',1,1.1,1.1,1.1,1.1,'Programador Junior','Client SM','alvaro.fa@test.com','77654',1,'3',1);
INSERT INTO `` (`idEmpleado`,`fechaIng`,`nombre`,`apellidoP`,`apellidoM`,`antiguedad`,`nivPeople`,`nivCraft`,`nivBusiness`,`nivOverall`,`puesto`,`equipo`,`email`,`password`,`fk_idChapter`,`fk_idRolJer`,`isActive`) VALUES (5,'2019-08-19','Jose','Alferez','Torres',2,3.1,3.1,3.1,3.1,'Lider de Programadores','ZeCore CRM','jose.at@test.com','ghfdgdf',1,'2',1);
INSERT INTO `` (`idEmpleado`,`fechaIng`,`nombre`,`apellidoP`,`apellidoM`,`antiguedad`,`nivPeople`,`nivCraft`,`nivBusiness`,`nivOverall`,`puesto`,`equipo`,`email`,`password`,`fk_idChapter`,`fk_idRolJer`,`isActive`) VALUES (6,'2019-03-19','Jorge','Martinez','Quiroz',2,3.2,3.1,3.1,3.1,'Proyect Manager','ZeCore Shipping','jorge.mq@test.mx','bxfcbdf',1,'2',1);
INSERT INTO `` (`idEmpleado`,`fechaIng`,`nombre`,`apellidoP`,`apellidoM`,`antiguedad`,`nivPeople`,`nivCraft`,`nivBusiness`,`nivOverall`,`puesto`,`equipo`,`email`,`password`,`fk_idChapter`,`fk_idRolJer`,`isActive`) VALUES (7,'2019-04-01','Diego','Velazquez','Juarez',2,2.4,3.1,3.1,2.5,'Supervisor','ZeCore Client','diego.vj@test.com','8fdja82',1,'2',1);
INSERT INTO `` (`idEmpleado`,`fechaIng`,`nombre`,`apellidoP`,`apellidoM`,`antiguedad`,`nivPeople`,`nivCraft`,`nivBusiness`,`nivOverall`,`puesto`,`equipo`,`email`,`password`,`fk_idChapter`,`fk_idRolJer`,`isActive`) VALUES (8,'2020-08-20','Rodrigo','Marquina','Perez',1,2.1,2.1,2.1,2.1,'Programador Senior','Client SM','rodrigo.mp@test.com','gsvreevd',1,'3',1);
INSERT INTO `` (`idEmpleado`,`fechaIng`,`nombre`,`apellidoP`,`apellidoM`,`antiguedad`,`nivPeople`,`nivCraft`,`nivBusiness`,`nivOverall`,`puesto`,`equipo`,`email`,`password`,`fk_idChapter`,`fk_idRolJer`,`isActive`) VALUES (9,'2020-05-31','Jaime','Chavez','Godinez',1,1.5,1.4,1.4,1.4,'Pogramador Pleno','ZeCore WMS','jaime.cg@test.com','6453ge',1,'3',1);
INSERT INTO `` (`idEmpleado`,`fechaIng`,`nombre`,`apellidoP`,`apellidoM`,`antiguedad`,`nivPeople`,`nivCraft`,`nivBusiness`,`nivOverall`,`puesto`,`equipo`,`email`,`password`,`fk_idChapter`,`fk_idRolJer`,`isActive`) VALUES (10,'2019-04-05','Isabela','Vales','Chavarria',2,2.4,2.4,2.4,2.4,'Supervisor','ZeCore WMS','isabela.vc@test.com','fgvsdvcs',1,'3',1);
INSERT INTO `` (`idEmpleado`,`fechaIng`,`nombre`,`apellidoP`,`apellidoM`,`antiguedad`,`nivPeople`,`nivCraft`,`nivBusiness`,`nivOverall`,`puesto`,`equipo`,`email`,`password`,`fk_idChapter`,`fk_idRolJer`,`isActive`) VALUES (11,'2022-03-19','Esteban','Talavera','Mendez',0,1.1,1.1,1.1,1.1,'Programador','ZeCore Client','esteban.tm@test.com','ggdawe',1,'3',1);
INSERT INTO `` (`idEmpleado`,`fechaIng`,`nombre`,`apellidoP`,`apellidoM`,`antiguedad`,`nivPeople`,`nivCraft`,`nivBusiness`,`nivOverall`,`puesto`,`equipo`,`email`,`password`,`fk_idChapter`,`fk_idRolJer`,`isActive`) VALUES (12,'2022-02-22','Valentina','Jimenez','Alvarez',0,1.1,1.1,1.1,1.1,'Tecnico','ZeCore Client','valentina.ja@test.com','ksklsdpej',1,'3',1);
INSERT INTO `` (`idEmpleado`,`fechaIng`,`nombre`,`apellidoP`,`apellidoM`,`antiguedad`,`nivPeople`,`nivCraft`,`nivBusiness`,`nivOverall`,`puesto`,`equipo`,`email`,`password`,`fk_idChapter`,`fk_idRolJer`,`isActive`) VALUES (13,'2022-03-01','Sergio','Nunez','Gongora',0,1.1,1.1,1.1,1.1,'Tecnico','ZeCore WMS','sergio.ng@test.com','939eh2',1,'3',1);
INSERT INTO `` (`idEmpleado`,`fechaIng`,`nombre`,`apellidoP`,`apellidoM`,`antiguedad`,`nivPeople`,`nivCraft`,`nivBusiness`,`nivOverall`,`puesto`,`equipo`,`email`,`password`,`fk_idChapter`,`fk_idRolJer`,`isActive`) VALUES (14,'2018-10-20','Marina','Reyes','Luna',3,4.1,4.1,4.1,4.1,'Proyect Manager','ZeCore Client','marina.rl@test.com','873in3sa',1,'1',1);
INSERT INTO `` (`idEmpleado`,`fechaIng`,`nombre`,`apellidoP`,`apellidoM`,`antiguedad`,`nivPeople`,`nivCraft`,`nivBusiness`,`nivOverall`,`puesto`,`equipo`,`email`,`password`,`fk_idChapter`,`fk_idRolJer`,`isActive`) VALUES (15,'2020-08-31','Diana','Bojorquez','Soto',1,3.5,3.5,3.5,3.5,'Supervisor','ZeCore Shipping','diana.bs@test.com','urke32',1,'2',1);
INSERT INTO `` (`idEmpleado`,`fechaIng`,`nombre`,`apellidoP`,`apellidoM`,`antiguedad`,`nivPeople`,`nivCraft`,`nivBusiness`,`nivOverall`,`puesto`,`equipo`,`email`,`password`,`fk_idChapter`,`fk_idRolJer`,`isActive`) VALUES (16,'2021-04-04','Andrea','Andrade','Galvez',0,1.2,1.2,1.2,1.2,'Programador','ZeCore WMS','andrea.ag@test.com','dfmvisdjf',1,'3',1);
INSERT INTO `` (`idEmpleado`,`fechaIng`,`nombre`,`apellidoP`,`apellidoM`,`antiguedad`,`nivPeople`,`nivCraft`,`nivBusiness`,`nivOverall`,`puesto`,`equipo`,`email`,`password`,`fk_idChapter`,`fk_idRolJer`,`isActive`) VALUES (17,'2020-05-21','Saul','Espinosa','Ramos',1,2.3,2.2,2.1,2.2,'Programador Pleno','ZeCore Shipping','saul.er@test.com','ncknd3',1,'2',1);
INSERT INTO `` (`idEmpleado`,`fechaIng`,`nombre`,`apellidoP`,`apellidoM`,`antiguedad`,`nivPeople`,`nivCraft`,`nivBusiness`,`nivOverall`,`puesto`,`equipo`,`email`,`password`,`fk_idChapter`,`fk_idRolJer`,`isActive`) VALUES (18,'2020-09-17','Jennifer','Mota','Rangel',1,2.1,2.1,2.2,2.1,'Programador Pleno','ZeCore WMS','jennifer.mr@test.com','1283osm',1,'2',1);
INSERT INTO `` (`idEmpleado`,`fechaIng`,`nombre`,`apellidoP`,`apellidoM`,`antiguedad`,`nivPeople`,`nivCraft`,`nivBusiness`,`nivOverall`,`puesto`,`equipo`,`email`,`password`,`fk_idChapter`,`fk_idRolJer`,`isActive`) VALUES (19,'2022-01-01','Melina','Santos','Degollado',0,1.2,1.3,1.3,1.2,'Asistente','ZeCore Shipping','melina.sd@test.com','0cvje3',1,'3',1);
INSERT INTO `` (`idEmpleado`,`fechaIng`,`nombre`,`apellidoP`,`apellidoM`,`antiguedad`,`nivPeople`,`nivCraft`,`nivBusiness`,`nivOverall`,`puesto`,`equipo`,`email`,`password`,`fk_idChapter`,`fk_idRolJer`,`isActive`) VALUES (20,'2019-07-07','Brenda','Reyes','Martinez',2,3.1,2.5,2.5,2.5,'Programador Senior','Client SM','brenda.rm@test.com','01udn34',1,'2',1);
