-- MySQL Script generated by MySQL Workbench
-- Tue Mar 29 09:21:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema testSIRE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Chapter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Chapter` (
  `idChapter` INT NOT NULL AUTO_INCREMENT,
  `nombreCh` VARCHAR(128) NOT NULL,
  `nEmpleados` INT NOT NULL,
  PRIMARY KEY (`idChapter`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RolJerarquico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RolJerarquico` (
  `idRolJer` INT NOT NULL AUTO_INCREMENT,
  `descRolJer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRolJer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `fechaIng` DATE NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoP` VARCHAR(45) NOT NULL,
  `apellidoM` VARCHAR(45) NOT NULL,
  `antiguedad` INT NOT NULL,
  `nivPeople` FLOAT NOT NULL,
  `nivCraft` FLOAT NOT NULL,
  `nivBusiness` FLOAT NOT NULL,
  `nivOverall` FLOAT NOT NULL,
  `puesto` VARCHAR(128) NOT NULL,
  `equipo` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `fk_idChapter` INT NOT NULL,
  `fk_idRolJer` INT NOT NULL,
  `isActive` TINYINT NULL,
  PRIMARY KEY (`idEmpleado`, `fk_idChapter`, `fk_idRolJer`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `idEmpleado_UNIQUE` (`idEmpleado` ASC) VISIBLE,
  INDEX `fk_Empleado_Chapter1_idx` (`fk_idChapter` ASC) VISIBLE,
  INDEX `fk_Empleado_RolJerarquico1_idx` (`fk_idRolJer` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Chapter1`
    FOREIGN KEY (`fk_idChapter`)
    REFERENCES `Chapter` (`idChapter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_RolJerarquico1`
    FOREIGN KEY (`fk_idRolJer`)
    REFERENCES `RolJerarquico` (`idRolJer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PeriodoEvaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PeriodoEvaluacion` (
  `idPeriodo` INT NOT NULL AUTO_INCREMENT,
  `FechaInicio` DATE NOT NULL,
  `FechaFin` DATE NOT NULL,
  PRIMARY KEY (`idPeriodo`),
  UNIQUE INDEX `idPeriodo_UNIQUE` (`idPeriodo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Template` (
  `idTemplate` INT NOT NULL AUTO_INCREMENT,
  `NombreTemplate` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`idTemplate`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cuestionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cuestionario` (
  `idCuestionario` INT NOT NULL AUTO_INCREMENT,
  `fk_idPeriodo` INT NOT NULL,
  `fk_idEvaluador` INT NOT NULL,
  `fk_idTemplate` INT NOT NULL,
  `idEvaluado` INT NOT NULL,
  `nivelEvaluado` FLOAT NULL,
  `isAnswered` TINYINT NULL,
  PRIMARY KEY (`idCuestionario`, `fk_idPeriodo`, `fk_idEvaluador`, `fk_idTemplate`),
  INDEX `fk_Cuestionario_Empleado1_idx` (`fk_idEvaluador` ASC) VISIBLE,
  INDEX `fk_Cuestionario_Empleado2_idx` (`idEvaluado` ASC) VISIBLE,
  INDEX `fk_Cuestionario_PeriodoEvaluacion1_idx` (`fk_idPeriodo` ASC) VISIBLE,
  INDEX `fk_Cuestionario_Template1_idx` (`fk_idTemplate` ASC) VISIBLE,
  CONSTRAINT `fk_Cuestionario_Empleado1`
    FOREIGN KEY (`fk_idEvaluador`)
    REFERENCES `Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cuestionario_Empleado2`
    FOREIGN KEY (`idEvaluado`)
    REFERENCES `Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cuestionario_PeriodoEvaluacion1`
    FOREIGN KEY (`fk_idPeriodo`)
    REFERENCES `PeriodoEvaluacion` (`idPeriodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cuestionario_Template1`
    FOREIGN KEY (`fk_idTemplate`)
    REFERENCES `Template` (`idTemplate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pregunta` (
  `idPregunta` INT NOT NULL AUTO_INCREMENT,
  `descPregunta` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`idPregunta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoPreguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoPreguntas` (
  `idBancoP` INT NOT NULL AUTO_INCREMENT,
  `fk_idTemplate` INT NOT NULL,
  `fk_idPregunta` INT NOT NULL,
  `tipoPregunta` TINYINT NOT NULL,
  PRIMARY KEY (`idBancoP`, `fk_idTemplate`, `fk_idPregunta`),
  INDEX `fk_Cuestionario_has_Pregunta_Pregunta1_idx` (`fk_idPregunta` ASC) VISIBLE,
  INDEX `fk_BancoPreguntas_Template1_idx` (`fk_idTemplate` ASC) VISIBLE,
  CONSTRAINT `fk_Cuestionario_has_Pregunta_Pregunta1`
    FOREIGN KEY (`fk_idPregunta`)
    REFERENCES `Pregunta` (`idPregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BancoPreguntas_Template1`
    FOREIGN KEY (`fk_idTemplate`)
    REFERENCES `Template` (`idTemplate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RolSistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RolSistema` (
  `idRolSis` INT NOT NULL AUTO_INCREMENT,
  `RolSis` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRolSis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RegistroAuth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RegistroAuth` (
  `fk_idEmpleado` INT NOT NULL,
  `fk_idRolSis` VARCHAR(15) NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`fk_idEmpleado`, `fk_idRolSis`),
  INDEX `fk_Empleado_has_RolSistema_RolSistema1_idx` (`fk_idRolSis` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_has_RolSistema_Empleado1`
    FOREIGN KEY (`fk_idEmpleado`)
    REFERENCES `Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_has_RolSistema_RolSistema1`
    FOREIGN KEY (`fk_idRolSis`)
    REFERENCES `RolSistema` (`idRolSis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Permisos` (
  `idFuncSis` INT NOT NULL AUTO_INCREMENT,
  `Funcion` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`idFuncSis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AsignacionPermisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AsignacionPermisos` (
  `fk_idRolSis` INT NOT NULL,
  `fk_idFuncSis` INT NOT NULL,
  PRIMARY KEY (`fk_idRolSis`, `fk_idFuncSis`),
  INDEX `fk_RolSistema_has_FuncionesSistema_FuncionesSistema1_idx` (`fk_idFuncSis` ASC) VISIBLE,
  INDEX `fk_RolSistema_has_FuncionesSistema_RolSistema1_idx` (`fk_idRolSis` ASC) VISIBLE,
  CONSTRAINT `fk_RolSistema_has_FuncionesSistema_RolSistema1`
    FOREIGN KEY (`fk_idRolSis`)
    REFERENCES `RolSistema` (`idRolSis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RolSistema_has_FuncionesSistema_FuncionesSistema1`
    FOREIGN KEY (`fk_idFuncSis`)
    REFERENCES `Permisos` (`idFuncSis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ChapterMood`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChapterMood` (
  `idChapterMood` INT NOT NULL AUTO_INCREMENT,
  `Mood` INT NULL,
  `Status` TINYINT NULL,
  `fk_idEmpleado` INT NOT NULL,
  `fk_idPeriodo` INT NOT NULL,
  PRIMARY KEY (`idChapterMood`, `fk_idEmpleado`, `fk_idPeriodo`),
  INDEX `fk_ChapterMood_Empleado1_idx` (`fk_idEmpleado` ASC) VISIBLE,
  INDEX `fk_ChapterMood_PeriodoEvaluacion1_idx` (`fk_idPeriodo` ASC) VISIBLE,
  CONSTRAINT `fk_ChapterMood_Empleado1`
    FOREIGN KEY (`fk_idEmpleado`)
    REFERENCES `Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ChapterMood_PeriodoEvaluacion1`
    FOREIGN KEY (`fk_idPeriodo`)
    REFERENCES `PeriodoEvaluacion` (`idPeriodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PreguntaRespuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PreguntaRespuesta` (
  `idRespuesta` INT NOT NULL AUTO_INCREMENT,
  `fk_idCuestionario` INT NOT NULL,
  `Template` INT NULL,
  `idPregunta` INT NULL,
  `Pregunta` VARCHAR(128) NULL,
  `Respuesta` VARCHAR(256) NULL,
  PRIMARY KEY (`idRespuesta`, `fk_idCuestionario`),
  INDEX `fk_PreguntaRespuesta_Cuestionario_idx` (`fk_idCuestionario` ASC) VISIBLE,
  CONSTRAINT `fk_PreguntaRespuesta_Cuestionario`
    FOREIGN KEY (`fk_idCuestionario`)
    REFERENCES `Cuestionario` (`idCuestionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Retroalimentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Retroalimentacion` (
  `idRetro` INT NOT NULL AUTO_INCREMENT,
  `Observaciones` VARCHAR(256) NULL,
  `fk_idCuestionario` INT NOT NULL,
  PRIMARY KEY (`idRetro`, `fk_idCuestionario`),
  INDEX `fk_Retroalimentacion_Cuestionario1_idx` (`fk_idCuestionario` ASC) VISIBLE,
  CONSTRAINT `fk_Retroalimentacion_Cuestionario1`
    FOREIGN KEY (`fk_idCuestionario`)
    REFERENCES `Cuestionario` (`idCuestionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mentees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mentees` (
  `idMentees` INT NOT NULL AUTO_INCREMENT,
  `fk_idLead` INT NOT NULL,
  `idMentee` INT NULL,
  `descAsignacion` VARCHAR(128) NULL,
  PRIMARY KEY (`idMentees`, `fk_idLead`),
  INDEX `fk_Mentees_Empleado1_idx` (`fk_idLead` ASC) VISIBLE,
  INDEX `fk_Mentees_Empleado2_idx` (`idMentee` ASC) VISIBLE,
  CONSTRAINT `fk_Mentees_Empleado1`
    FOREIGN KEY (`fk_idLead`)
    REFERENCES `Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mentees_Empleado2`
    FOREIGN KEY (`idMentee`)
    REFERENCES `Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;